---
title: "Fig 5.21 Brownlee Reservoir"
format: html
---

## Setup
```{r}
#| message: false

knitr::opts_chunk$set(out.width = "60%", fig.width = 5, fig.height = 4)

library(tidyverse)
library(readxl)
library(janitor)
library(patchwork)
library(ggrepel)

d <- read_excel("Data/Fig. 5.21 Brownlee.xlsx", range = "B3:H11") |>
  clean_names() |>
  slice(-1) |>
  rename_with(.cols = -1, \(x) str_extract(x, "tp|drp|chl") |> paste0(c("_1999", "_2000"))) |>
  pivot_longer(-rm, 
               names_to = c("measure", "year"), 
               names_sep = "_(?=\\d{4})") |>
  pivot_wider(names_from = "measure", values_from = "value")

blu <- "blue3" # Standard point colour
```


## Figure

```{r}
#| fig-width: 5
#| fig-height: 6
#| fig-dpi: 800
#| out-width: 80%

# y-Log base plot
g0 <- ggplot(d, aes(x = rm, colour = year, shape = year, fill = year)) +
  theme_classic(base_size = 12) +
  theme(plot.margin = margin(), plot.tag.position = c("topleft")) +
  scale_x_reverse(name = "Location (River Mile)", limits = c(345, 283), breaks = seq(340, 290, -10)) +
  scale_colour_manual(name = "", values = c("1999" = blu, "2000" = "deepskyblue"), aesthetics = c("fill", "colour")) +
  scale_shape_manual(name = "", values = c("1999" = 21, "2000" = 22))

290 + 0.5 * (315 - 290)
315 + 0.5 * (335 - 315)

g00 <- g0 +
  scale_y_continuous(limits = c(0.05, 0.55)) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), 
        axis.line = element_blank()) +
  # Inflow
  annotate(geom = "text", label = "Inflow", x = 345, y = 0.5) +
  annotate(geom = "segment", arrow = arrow(type = "closed", length = unit(2, "mm")),
           x = 345, xend = 345, y = 0.35, yend = 0.1) +
  # Outflow
  annotate(geom = "text", label = "Outflow", x = 284.5, y = 0.5) +
  annotate(geom = "segment", arrow = arrow(type = "closed", length = unit(2, "mm")),
           x = 284, xend = 284, y = 0.35, yend = 0.1) +
  # Depths
  annotate(geom = "text", label = "Shallow", x = 325, y = 0.5) +
  annotate(geom = "text", label = "Deep", x = 302.5, y = 0.5) +
  annotate(geom = "segment", linetype = "dashed", x = 332.5, xend = 317.5, y = 0.3, yend = 0.3, colour = "grey") +
  annotate(geom = "segment", linetype = "dashed", x = 292.5, xend = 312.5, y = 0.3, yend = 0.3, colour = "grey") +
  plot_layout(tag_level = "new")
  
g0 <- g0 +
  geom_vline(xintercept = c(315, 335), colour = "grey")
  

g1 <- g0 +
  theme(axis.title.x = element_blank(), legend.position = "none") +
  geom_line(aes(y = tp)) +
  geom_point(aes(y = tp)) +
  scale_y_continuous(name = bquote("TP"~(m*g/L)), limits = c(0, 0.170))

g2 <- g0 +
  theme(legend.position = "none") +
  geom_line(aes(y = drp)) +
  geom_point(aes(y = drp)) +
  scale_y_continuous(name = bquote("SRP"~(m*g/L)), limits = c(0, 0.06))

g3 <- g0 +
  theme(axis.title.x = element_blank(), 
        legend.position = "inside", legend.justification = c(0.9, 1)) +
  geom_line(aes(y = chl)) +
  geom_point(aes(y = chl)) +
  scale_y_continuous(limits = c(0, 50), name = bquote("Chlorophyll"~(mu*g/L)))


gg <- g00 / g3 / g1 / g2 + plot_annotation(tag_levels = "A", tag_prefix = "(", tag_suffix = ")") +
  plot_layout(heights = c(1, 3, 3, 3))

gg

```
